version: '3.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092'
      - '9094:9094'
    depends_on:
      - 'zookeeper'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'INSIDE://kafka:9092,OUTSIDE://kafka:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INSIDE://kafka:9092,OUTSIDE://${EXTERNAL_IP}:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 500
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${KAFKA_DATA}/500:/kafka'
  kafka-2:
    image: wurstmeister/kafka
    ports:
      - '9092'
      - '9095:9095'
    depends_on:
      - 'zookeeper'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'INSIDE://kafka-2:9092,OUTSIDE://kafka-2:9095'
      KAFKA_ADVERTISED_LISTENERS: 'INSIDE://kafka-2:9092,OUTSIDE://${EXTERNAL_IP}:9095'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 501
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${KAFKA_DATA}/501:/kafka'
  kafka-3:
    image: wurstmeister/kafka
    ports:
      - '9092'
      - '9096:9096'
    depends_on:
      - 'zookeeper'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'INSIDE://kafka-3:9092,OUTSIDE://kafka-3:9096'
      KAFKA_ADVERTISED_LISTENERS: 'INSIDE://kafka-3:9092,OUTSIDE://${EXTERNAL_IP}:9096'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 502
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${KAFKA_DATA}/502:/kafka'
  kafka-ui:
    image: kafkamanager/kafka-manager:3.0.0.4
    environment:
      ZK_HOSTS: 'zookeeper:2181'
    ports:
      - '9000:9000'
    depends_on:
      - 'zookeeper'
      - 'kafka'
      - 'kafka-2'
      - 'kafka-3'
